// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: doc_cache.sql

package database

import (
	"context"
)

const upsertDocCache = `-- name: UpsertDocCache :exec
INSERT INTO doc_cache (repo_url, commit_sha, doc_type, content)
VALUES ($1, $2, $3, $4)
ON CONFLICT (repo_url, commit_sha, doc_type)
DO UPDATE SET content    = EXCLUDED.content,
             expires_at = now() + INTERVAL '7 days'
`

type UpsertDocCacheParams struct {
	RepoUrl   string `json:"repo_url"`
	CommitSha string `json:"commit_sha"`
	DocType   string `json:"doc_type"`
	Content   string `json:"content"`
}

func (q *Queries) UpsertDocCache(ctx context.Context, arg UpsertDocCacheParams) error {
	_, err := q.db.Exec(ctx, upsertDocCache,
		arg.RepoUrl,
		arg.CommitSha,
		arg.DocType,
		arg.Content,
	)
	return err
}
