// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertDocument = `-- name: UpsertDocument :exec
INSERT INTO documents (job_id, doc_type, content, prompt_tokens, completion_tokens)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (job_id, doc_type)
DO UPDATE SET content           = EXCLUDED.content,
             prompt_tokens     = EXCLUDED.prompt_tokens,
             completion_tokens = EXCLUDED.completion_tokens
`

type UpsertDocumentParams struct {
	JobID            pgtype.UUID `json:"job_id"`
	DocType          string      `json:"doc_type"`
	Content          string      `json:"content"`
	PromptTokens     pgtype.Int4 `json:"prompt_tokens"`
	CompletionTokens pgtype.Int4 `json:"completion_tokens"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) error {
	_, err := q.db.Exec(ctx, upsertDocument,
		arg.JobID,
		arg.DocType,
		arg.Content,
		arg.PromptTokens,
		arg.CompletionTokens,
	)
	return err
}
