// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobsByUser = `-- name: CountJobsByUser :one
SELECT COUNT(*) FROM jobs WHERE user_id = $1
`

func (q *Queries) CountJobsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (user_id, repo_url, branch)
VALUES ($1, $2, $3)
RETURNING id, user_id, repo_url, branch, commit_sha, status, error_message, file_count, gemini_calls_used, started_at, completed_at, created_at, updated_at
`

type CreateJobParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	RepoUrl string      `json:"repo_url"`
	Branch  pgtype.Text `json:"branch"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.UserID, arg.RepoUrl, arg.Branch)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoUrl,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.ErrorMessage,
		&i.FileCount,
		&i.GeminiCallsUsed,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :execrows
DELETE FROM jobs WHERE id = $1 and user_id = $2
`

type DeleteJobParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteJob(ctx context.Context, arg DeleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteJob, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, user_id, repo_url, branch, commit_sha, status, error_message, file_count, gemini_calls_used, started_at, completed_at, created_at, updated_at FROM jobs WHERE id = $1 and user_id = $2
`

type GetJobParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.UserID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoUrl,
		&i.Branch,
		&i.CommitSha,
		&i.Status,
		&i.ErrorMessage,
		&i.FileCount,
		&i.GeminiCallsUsed,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingJob = `-- name: GetPendingJob :many
SELECT id, user_id, repo_url, branch, commit_sha, status, error_message, file_count, gemini_calls_used, started_at, completed_at, created_at, updated_at FROM jobs
WHERE status = 'pending'
`

func (q *Queries) GetPendingJob(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, getPendingJob)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoUrl,
			&i.Branch,
			&i.CommitSha,
			&i.Status,
			&i.ErrorMessage,
			&i.FileCount,
			&i.GeminiCallsUsed,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByUser = `-- name: ListJobsByUser :many
SELECT id, user_id, repo_url, branch, commit_sha, status, error_message, file_count, gemini_calls_used, started_at, completed_at, created_at, updated_at FROM jobs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListJobsByUser(ctx context.Context, arg ListJobsByUserParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoUrl,
			&i.Branch,
			&i.CommitSha,
			&i.Status,
			&i.ErrorMessage,
			&i.FileCount,
			&i.GeminiCallsUsed,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
