// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DocCache struct {
	ID        pgtype.UUID        `json:"id"`
	RepoUrl   string             `json:"repo_url"`
	CommitSha string             `json:"commit_sha"`
	DocType   string             `json:"doc_type"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Document struct {
	ID               pgtype.UUID        `json:"id"`
	JobID            pgtype.UUID        `json:"job_id"`
	DocType          string             `json:"doc_type"`
	Content          string             `json:"content"`
	PromptTokens     pgtype.Int4        `json:"prompt_tokens"`
	CompletionTokens pgtype.Int4        `json:"completion_tokens"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	RepoUrl         string             `json:"repo_url"`
	Branch          pgtype.Text        `json:"branch"`
	CommitSha       pgtype.Text        `json:"commit_sha"`
	Status          string             `json:"status"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	FileCount       pgtype.Int4        `json:"file_count"`
	GeminiCallsUsed pgtype.Int4        `json:"gemini_calls_used"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	GithubTokenEnc pgtype.Text        `json:"github_token_enc"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
