// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, github_token_enc, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GithubTokenEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGithubToken = `-- name: DeleteGithubToken :exec
UPDATE users
SET github_token_enc = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) DeleteGithubToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGithubToken, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, github_token_enc, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GithubTokenEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, github_token_enc, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GithubTokenEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGithubToken = `-- name: UpdateGithubToken :exec
UPDATE users
SET github_token_enc = $2, updated_at = now()
WHERE id = $1
`

type UpdateGithubTokenParams struct {
	ID             pgtype.UUID `json:"id"`
	GithubTokenEnc pgtype.Text `json:"github_token_enc"`
}

func (q *Queries) UpdateGithubToken(ctx context.Context, arg UpdateGithubTokenParams) error {
	_, err := q.db.Exec(ctx, updateGithubToken, arg.ID, arg.GithubTokenEnc)
	return err
}
